name: quick_start
description: "A new Flutter project."
version: 1.9.0
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  # 现有依赖
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  window_manager: ^0.3.7
  hotkey_manager: ^0.2.3
  flutter_localizations:
    sdk: flutter
  intl: any
  auto_updater: ^1.0.0
  package_info_plus: ^4.2.0
  connectivity_plus: ^5.0.1
  sqflite_common_ffi: ^2.3.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5

  win32: ^5.0.0
  ffi: ^2.1.0
  desktop_drop: ^0.4.4
  yaml: ^3.1.2  

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.7
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
